# Generated by Django 4.2.6 on 2023-10-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.ManyToManyField(to='main.topic'),
        ),
    ]
