# Generated by Django 4.2.6 on 2023-11-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.ManyToManyField(related_name='article_topics', to='main.topic'),
        ),
    ]
